### ISSUE TITLE
【建议】为dock栏添加放大效果 

### ISSUE THREAD

**Issue by SDCOM-0415** [CodeCrafter-TL/x-html#10]
**描述错误**
dock栏没有合适的放大效果

**重现**
重现行为的步骤：
1. 移动到dock栏
2. 仅有软件名称，但没有放大效果

**预期行为**
能够拥有放大效果

**屏幕截图**

https://github.com/CodeCrafter-TL/x-html/assets/127208666/ce740d19-c9d5-4262-880b-db38fb7a527f

**使用设备：**
 - 系统：macOS sequoia b2
 - 浏览器：Microsoft Edge
 - 版本：126.0.2592.87 (正式版本) (x86_64)

**其他背景信息**
暂无

**Comment by CodeCrafter-TL** [comment]
如原本的macOS，刚刚安装时是默认不会开启程序坞放大效果的，后期如果条件允许会在“系统设置”里添加此选项。

**Comment by SDCOM-0415** [comment]
了解
