### ISSUE TITLE
【建议】将issues模板编写为中文以及添加建议模版

### ISSUE THREAD

**Issue by SDCOM-0415** [CodeCrafter-TL/x-html#11]
添加中文的bug issues 提交模版
增加建议模版，这里可以提供一些建议：

**想要提出的建议**
清晰简洁地描述建议是什么。

**预期实现的效果**
达到预期实现效果的步骤：
1. 转到“...”
2. 单击“....”
3. 向下滚动到“....”
4. 查看效果

**屏幕截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**使用设备（请填写以下信息）：**
- 设备类型：[例如 iPhone 15]
- 操作系统：[例如 iOS]
- 浏览器： [例如 chrome、safari]
- 版本： [例如 22]

**其他背景信息**
在此添加有关该预期效果的的任何其他背景信息。

**Comment by CodeCrafter-TL** [comment]
已添加
