### ISSUE TITLE
【建议】优化代码&工程化重构

### ISSUE THREAD

**Issue by NaHCO3-code** [CodeCrafter-TL/x-html#5]
目前代码组织存在很多问题，如：
- script全写在html里
- 大量内联css

现在项目规模较小，但如果持续开发，可能很快出现难以阅读和维护的代码。

如果可能，建议使用 `vite`, `vue`, `react`, `svelte` 等框架重构。

另外，我注意到 `index.html` 存在大量的 `setTimeout` 嵌套。JavaScript早期确实不得不写这种代码，叫做“回调地狱”。但是现在已经有更好的解决方案，如 [Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Using_promises), [async/await](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function) 等 [异步](https://developer.mozilla.org/zh-CN/docs/Glossary/Asynchronous) 的 JavaScript API. 具体请看 [MDN的这些文章](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Asynchronous)。

总的来说，我很佩服你们的勇气，但是确实有很多需要学习和改进之处。

**Comment by CodeCrafter-TL** [comment]
好的好的！！我会尝试改进的！总之谢谢您的建议！

**Comment by NaHCO3-code** [comment]
#6

**Comment by CodeCrafter-TL** [comment]
麻烦查看一下您的Pull Request。
