### ISSUE TITLE
【BUG (May-be】使用的过程中发现任何APP关闭后无法再次打开

### ISSUE THREAD

**Issue by HelloAIXIAOJI** [CodeCrafter-TL/x-html#7]
**描述错误**
使用的过程中发现任何APP关闭后无法再次打开

**重现**
重现行为的步骤：
- 打开“系统设置”
- 关闭“系统设置”
- 复现：无法再次打开“系统设置”
- 演示使用的是“系统设置”，但波及所有的DUCK栏与启动台程序

**预期行为**
应该能够正常打开

**屏幕截图**

https://github.com/CodeCrafter-TL/x-html/assets/87511694/708b11cc-c315-44c7-b635-0883985dc9ec

**桌面**
- 操作系统：Windows 11
- 浏览器：  Microsoft Edge
- 版本：126.0.2592.81 (正式版本) (64 位)

**其他背景信息**
- 镜像与github.io站都试过，因此可以断定此BUG非VPN软件造成

**Comment by CodeCrafter-TL** [comment]
我知道这个潜在的Bug，日后会修复

**Comment by CodeCrafter-TL** [comment]
7.0.3已修复，感谢您的支持
