### ISSUE TITLE
The password input element has a black border

### ISSUE THREAD

**Issue by kyle12678** [CodeCrafter-TL/x-html#8]
**Describe the bug**
The password input element has a black border

**To Reproduce**
1. Open logon page
2. Click the password input element

**Expected behavior**
Remove the black border

**Screenshots**
![image](https://github.com/CodeCrafter-TL/x-html/assets/54564019/07b31485-4fa5-4dbd-a517-8836ed977aab)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 126

**Comment by CodeCrafter-TL** [comment]
This border will only appear in the Windows environment, because this is the UI inside the system.
